### ISSUE TITLE
Support different versions of a particular CDE

### ISSUE THREAD

**Issue by gaurav** [HOT-Ecosystem/cadsr-on-fhir#2]
When accessing https://fhir.hotecosystem.org/terminology/cadsr/ValueSet/2178467, I get v1.0 of the CDE. However, the most recent version of this CDE is [v4.0](https://cdebrowser.nci.nih.gov/cdebrowserClient/cdeBrowser.html#/search?publicId=2178467&version=4.0). Is there a way of accessing v4.0 of this CDE via the FHIR interface?

**Comment by jiaola** [comment]
@gaurav Nice catch!

It's a bug. The code not mapped to NCIt code is not returned by the service. I'll fix that. 

The version is actually correct. The data is based on the recent CDE in caDSR. The value set is based on the value domain of the CDE, which has a different version than the CDE. The value domain of the record in the example is [1.0](https://cdebrowser.nci.nih.gov/cdebrowserClient/cdeBrowser.html#/valueDomain)

**Comment by gaurav** [comment]
Gotcha. Thanks!

It would be nice to include the CDE version in the output as well so we know which one was used. I think it might eventually be useful to allow users to choose a particular version of the CDE also, but I don't have a specific use case for that yet.

**Comment by jiaola** [comment]
Got it. I think right now choosing a CDE version is not possible from the service. The reason is that the RDF data only contains a snapshot of the caDSR, not all the versions. Down the road, we should consider asking for RDF of previous versions.

**Comment by jiaola** [comment]
@gaurav I've pushed the change to the server. If everything looks ok, please close this ticket. We can open a new one when there are use cases for multi-version caDSR supports. Thx!
