### ISSUE TITLE
caDSR-on-FHIR down?

### ISSUE THREAD

**Issue by gaurav** [HOT-Ecosystem/cadsr-on-fhir#6]
Hi there! I can't access https://fhir.hotecosystem.org/terminology/cadsr/ValueSet/5432687 -- is fhir.hotecosystem.org down? No worries if it is -- I'm just opening this issue so you can let me know once it's back up, or -- if it's down permanently -- so I can switch over to another caDSR query service. Thanks!

**Comment by jiaola** [comment]
@gaurav Thanks for bringing it to our attention! The server is still running but the subdomain fhir.hotecosystem.org has been taken off it. I'm working with Shahim who owns the domain to put it back. 

Meanwhile, you can access the service directly via the IP address. Note don't use https, just use http. 

http://18.208.244.223/terminology/cadsr/ValueSet/5432687

**Comment by gaurav** [comment]
Thanks, Dazhi!

**Comment by jiaola** [comment]
@gaurav  I've put the fhir.hotecosystem.org domain back, and took away the IP based url. 

So please continue to use the following to access the service. 

https://fhir.hotecosystem.org/terminology/cadsr/ValueSet/5432687

Sorry for the interruption!
